import{CATEGORIES,storageMode,signIn,listProducts,makeCode,saveProduct,updateProduct,deleteProduct,uploadProductImage}from"./data-service.js?v=1";
const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let products=[],token=sessionStorage.getItem("littlenest-token")||"",selectedCategory="Semua",editing=null,pendingDelete=null,imageUrl="";
const loginScreen=$("login-screen"),app=$("manager-app"),list=$("manager-list"),drawer=$("product-drawer"),backdrop=$("drawer-backdrop"),form=$("product-form");
const money=n=>`RM ${Number(n||0).toFixed(2)}`;
function toast(message,type="ok"){const el=$("toast");el.textContent=message;el.className=`toast show ${type}`;setTimeout(()=>el.className="toast",2600);}
function showApp(email="Pemilik Kedai"){loginScreen.classList.add("hidden");app.classList.remove("hidden");$("manager-email").textContent=email;load();}
async function load(){try{products=await listProducts({includeHidden:true});render();}catch(e){toast(e.message,"error");}}
function renderTabs(){const tabs=$("manager-tabs");tabs.innerHTML=CATEGORIES.map(x=>`<button class="${x===selectedCategory?"active":""}" data-category="${esc(x)}">${esc(x)}</button>`).join("");}
function render(){renderTabs();const q=$("manager-search").value.trim().toLowerCase();const visible=products.filter(x=>(selectedCategory==="Semua"||x.category===selectedCategory)&&(!q||`${x.name} ${x.code}`.toLowerCase().includes(q)));$("manager-count").textContent=products.length;list.innerHTML=visible.map(item=>`<article class="manager-row" data-id="${esc(item.id)}"><div class="manager-product"><img src="${esc(item.image_url||"assets/littlenest-logo.png")}" alt=""><div><small>${esc(item.code)}</small><strong>${esc(item.name)}</strong></div></div><strong class="row-price">${money(item.price)}</strong><div class="stock-control"><button data-action="stock-down" aria-label="Kurangkan stok">−</button><b>${Number(item.stock)||0}</b><button data-action="stock-up" aria-label="Tambah stok">＋</button></div><span>${esc(item.category)}</span><span class="status ${item.active?"active":"hidden-status"}">${item.active?"Dipaparkan":"Disorok"}</span><div class="row-actions"><button data-action="edit">Edit</button><button data-action="toggle">${item.active?"Sorok":"Papar"}</button><button class="delete" data-action="delete">Buang</button></div></article>`).join("");$("manager-empty").classList.toggle("hidden",visible.length>0);}
function openDrawer(item=null){editing=item;imageUrl=item?.image_url||"";$("drawer-title").textContent=item?"Edit Barang":"Tambah Barang";$("product-id").value=item?.id||"";$("product-code").value=item?.code||"";$("product-name").value=item?.name||"";$("product-category").value=item?.category||"Baju";$("product-price").value=item?.price??"";$("product-stock").value=item?.stock??1;$("product-active").checked=item?.active??true;updatePreview();drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");backdrop.classList.remove("hidden");}
function closeDrawer(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");backdrop.classList.add("hidden");form.reset();editing=null;imageUrl="";updatePreview();}
function updatePreview(){const box=$("image-preview");box.classList.toggle("hidden",!imageUrl);if(imageUrl)box.querySelector("img").src=imageUrl;}
$("product-category").innerHTML=CATEGORIES.filter(x=>x!=="Semua").map(x=>`<option>${x}</option>`).join("");
$("login-form").addEventListener("submit",async e=>{e.preventDefault();const note=$("login-note");note.textContent="Sedang log masuk…";try{const data=await signIn($("login-email").value,$("login-password").value);token=data.access_token;sessionStorage.setItem("littlenest-token",token);sessionStorage.setItem("littlenest-email",data.user?.email||$("login-email").value);showApp(data.user?.email);note.textContent="";}catch(err){note.textContent=err.message;}});
$("logout-button").onclick=()=>{sessionStorage.removeItem("littlenest-token");sessionStorage.removeItem("littlenest-email");location.reload();};
$("add-product").onclick=()=>openDrawer();$("close-drawer").onclick=closeDrawer;$("cancel-product").onclick=closeDrawer;backdrop.onclick=closeDrawer;
$("manager-tabs").addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;selectedCategory=b.dataset.category;render();});$("manager-search").addEventListener("input",render);
$("product-file").addEventListener("change",e=>{const file=e.target.files[0];if(file){imageUrl=URL.createObjectURL(file);updatePreview();}});$("remove-image").onclick=()=>{imageUrl="";$("product-file").value="";updatePreview();};
form.addEventListener("submit",async e=>{e.preventDefault();const save=$("save-product");save.disabled=true;save.textContent="Menyimpan…";try{const category=$("product-category").value;const file=$("product-file").files[0];if(file)imageUrl=await uploadProductImage(file,token);const product={id:editing?.id,code:$("product-code").value.trim()||makeCode(category,products),name:$("product-name").value.trim(),category,price:Number($("product-price").value),stock:Number($("product-stock").value),image_url:imageUrl,active:$("product-active").checked,position:editing?.position||products.length+1};await saveProduct(product,token);closeDrawer();await load();toast("Barang berjaya disimpan");}catch(err){toast(err.message,"error");}finally{save.disabled=false;save.textContent="Simpan Barang";}});
list.addEventListener("click",async e=>{const button=e.target.closest("[data-action]");if(!button)return;const item=products.find(x=>String(x.id)===button.closest("[data-id]").dataset.id);if(!item)return;const action=button.dataset.action;if(action==="edit")return openDrawer(item);if(action==="delete"){pendingDelete=item;$("confirm-modal").classList.remove("hidden");return;}try{if(action==="toggle")await updateProduct(item.id,{active:!item.active},token);if(action==="stock-up")await updateProduct(item.id,{stock:Number(item.stock)+1},token);if(action==="stock-down")await updateProduct(item.id,{stock:Math.max(0,Number(item.stock)-1)},token);await load();toast("Perubahan disimpan");}catch(err){toast(err.message,"error");}});
$("cancel-delete").onclick=()=>{$("confirm-modal").classList.add("hidden");pendingDelete=null;};$("confirm-delete").onclick=async()=>{if(!pendingDelete)return;try{await deleteProduct(pendingDelete.id,token);$("confirm-modal").classList.add("hidden");pendingDelete=null;await load();toast("Barang telah dibuang");}catch(err){toast(err.message,"error");}};
renderTabs();if(token||storageMode==="demo")showApp(sessionStorage.getItem("littlenest-email")||"Pratonton Setempat");
